CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    genre_id INTEGER NOT NULL,
    is_borrowed INTEGER DEFAULT 0,
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);
